---
title: "Fish Analysis"
author: "Diana Young"
date: "2/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r wrap-hook, eval=TRUE, include=FALSE, echo=FALSE}
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})
```

## Required Packages

Load the packages that will be used in the analyses
```{r load_libraries, include = TRUE, collapse = TRUE}
library(car)
library(dplyr)
library(ggplot2)
library(knitr)
```

## Import Data

``` {r import_data, include = TRUE, collapse = TRUE}
FISH <- read.csv("Fish.csv", stringsAsFactors = TRUE)
summary(FISH)

```

### Data Exploration

We began our analysis by exploring each variable's distribution, measures of central tendency, and value domaine to determine if cleaning or variable transformations are required.  

### Density Plots

``` {density_plot, include = TRUE}

ggplot(FISH, aes(Weight, Length)) + geom_point()

```